
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author micla1676
 */
public class Translator_Jframe extends javax.swing.JFrame {

    /**
     * Creates new form Translator
     */
    public Translator_Jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        translate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        input.setText("Enter your word here");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        output.setEditable(false);
        output.setText("Translation");

        translate.setText("Translate");
        translate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(output)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(translate)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(translate)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void translateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_translateActionPerformed
        //convert input to a string
        String word = input.getText();
        
            //change word to lowercase
            word = word.toLowerCase();

            //find the length of the word and store it
            int length = word.length();

            //create pattern
            Pattern checkRegex = Pattern.compile("[aeiou]");
            //check pattern
            Matcher regexMatcher = checkRegex.matcher(word);
            //if match is found
            if (regexMatcher.find()) {

                //create a variable to store the location of first vowel in 
                //word
                int firstV = regexMatcher.start();
                //execute if index value of the first vowel is equal to zero
                if (firstV == 0) {

                    //seperate the word
                    //create a string to store first part of word
                    String Beginning = word.substring(0, 1);

                    //take the end of the word exluding the first Vowel and last
                    //letter
                    String middle = word.substring(firstV + 1, length - 1);
                    //take the last letter of the string
                    String End = word.substring(length - 1);

                    //create pattern
                    Pattern checkRegex3 = Pattern.compile("[aeiouy]");
                    //check pattern of aeiouy
                    Matcher regexMatcher4 = checkRegex3.matcher(End);
                    //if match is found
                    if (regexMatcher4.find()) {
                        //print translated word to screen
                        String finalWord =("i" + middle + End + "hee");
                        //output to second line
                         output.setText(finalWord);
                    } //if last letter is a constanant, print to screen
                    else {
                        String finalWord =("i" + middle + End + "ee");
                        //output to second line
                         output.setText(finalWord);
                    }
                } //if first vowel occours at an index greater then 0.
                else if (firstV > 0) {
                    //create pattern
                    Pattern checkRegex2 = Pattern.compile("[aeiouy]");
                    //check the pattern
                    Matcher regexMatcher3 = checkRegex2.matcher(word);
                    //if match is found
                    if (regexMatcher3.find()) {
                        //set firstV = to the index value of the first vowel
                        firstV = regexMatcher3.start();
                        //seperate the word
                        //create a string to store first part of word
                        String cBeginning = word.substring(0, firstV);
                        //take the end of the word exluding the first Vowel
                        String cEnd2 = word.substring(firstV + 1, length);
                        //print translated word to screen
                        String finalWord = ("i" + cEnd2 + cBeginning + "ee");
                        //output to second line
                         output.setText(finalWord);
                    }
                }
            }
        
                
         
      
    }//GEN-LAST:event_translateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Translator_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Translator_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Translator_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Translator_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Translator_Jframe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JTextField output;
    private javax.swing.JButton translate;
    // End of variables declaration//GEN-END:variables
}
